<a href="https://colab.research.google.com/github/Siddhartha127/Pytorch_Learning/blob/main/Pytorch_03_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
1. Simple Neural Network
2. Will Mimic the PyTorch workflow
3. Will have a lot of manual elements
5.End result is not important
```



```
# Code flow:
1.Laod Dataset
2.Basic preprocessing
3.Training Process
  a. Create a model
  b. Forward pass
  c. Loss calculation
  d. Backprop
  e. Parameters update
4. Model evaluation
```

In [38]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [39]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [40]:
df.shape

(569, 33)

In [41]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [42]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [43]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [44]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [45]:
X_train

array([[ 1.36289619,  0.57221081,  1.33109804, ...,  0.85579403,
         0.16363376, -0.06901423],
       [ 1.00480644, -0.98189813,  0.9704497 , ...,  0.47633288,
        -0.2443165 , -0.28310902],
       [-0.25566947,  0.53627765, -0.25575466, ...,  0.70370841,
         1.27858946,  0.63776959],
       ...,
       [-1.19930757, -0.48332561, -1.18846588, ..., -0.87466926,
         0.13437836, -0.57525356],
       [-0.49344106, -1.60623669, -0.52437549, ..., -0.10490522,
         0.33103965, -0.46034699],
       [ 0.7269288 ,  1.94440815,  0.69270902, ...,  0.41911255,
        -1.11872783, -0.33676822]])

In [46]:
y_train

433    M
29     M
44     M
372    M
524    B
      ..
420    B
231    B
206    B
527    B
566    M
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [47]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [48]:
y_train

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1])

# Numpy arrays to Pytorch Tensors

In [49]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [50]:
X_train_tensor.shape

torch.Size([455, 30])

In [51]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [52]:
class SimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64,requires_grad=True)

  def forward(self, X):
    z=torch.matmul(X,self.weights) + self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [53]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [54]:
#create model
model = SimpleNN(X_train_tensor)
# model.weights

#defining loop
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train_tensor)

  #Loss
  loss = model.loss_function(y_pred, y_train_tensor)
  #print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

  #backwad pass
  loss.backward() #autograd is used

  #parameter upgrade
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loff in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.471150415759204
Epoch: 2, Loss: 3.3473941156044438
Epoch: 3, Loss: 3.217472485050724
Epoch: 4, Loss: 3.081543924054271
Epoch: 5, Loss: 2.945914915321617
Epoch: 6, Loss: 2.803566590410268
Epoch: 7, Loss: 2.6587510583705827
Epoch: 8, Loss: 2.5101162892275526
Epoch: 9, Loss: 2.3609674117246673
Epoch: 10, Loss: 2.2092301819873548
Epoch: 11, Loss: 2.0563986753922263
Epoch: 12, Loss: 1.9039989874361838
Epoch: 13, Loss: 1.757431026516299
Epoch: 14, Loss: 1.614200708572022
Epoch: 15, Loss: 1.48098720498319
Epoch: 16, Loss: 1.3567427778111287
Epoch: 17, Loss: 1.2433960987394197
Epoch: 18, Loss: 1.145642190756216
Epoch: 19, Loss: 1.0637788661755412
Epoch: 20, Loss: 0.9972203725935727
Epoch: 21, Loss: 0.9445008933207188
Epoch: 22, Loss: 0.90350347338332
Epoch: 23, Loss: 0.8718369095600601
Epoch: 24, Loss: 0.8472121952200818
Epoch: 25, Loss: 0.8276964067200484

# Evaluatuion

In [56]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5914127230644226