<a href="https://colab.research.google.com/github/Siddhartha127/Pytorch_Learning/blob/main/Pytorch_04_NN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. The nn modeule
2. The torch.optim module

In [ ]:
import torch
import torch.nn as nn
#need to inherit nn.Module
class Model(nn.Module):
  def __init__(self,num_feature):
    #invoke parent class constructor using super keyword
    super().__init__()
    self.linear=nn.Linear(num_feature,1)
    self.sigmoid= nn.Sigmoid()
  def forward(self,feature):
    out = self.linear(features)
    out=self.sigmoid(out)
    return out

In [ ]:
#create dataset
features=torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forwarc pass
model(features)

tensor([[0.6584],
        [0.7228],
        [0.6252],
        [0.7220],
        [0.6811],
        [0.7117],
        [0.6989],
        [0.6855],
        [0.6627],
        [0.6596]], grad_fn=<SigmoidBackward0>)

In [ ]:
#shows model weights
model.linear.weight

Parameter containing:
tensor([[ 0.1213, -0.0023,  0.3423,  0.3032, -0.0391]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.3811], requires_grad=True)

In [ ]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [ ]:
from torchinfo import summary

summary(model, input_size=(10, 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

# NN with a hidden layer

5 inputs -> 3 neuron(hidden layer)->output neuron(y_pred)

18 weights 4 bias
relu in hidden layer and sigmoid i outpout

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out=self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [ ]:
#create dataset
features=torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forwarc pass
model(features)

tensor([[0.7013],
        [0.7183],
        [0.6667],
        [0.6941],
        [0.6945],
        [0.7016],
        [0.6631],
        [0.7162],
        [0.7231],
        [0.6949]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.0416,  0.3514,  0.3447, -0.3564, -0.0761],
        [ 0.2749,  0.1607, -0.0089,  0.0338, -0.0443],
        [ 0.3659,  0.4066,  0.4443,  0.0681, -0.1625]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[0.3228, 0.1706, 0.4006]], requires_grad=True)

In [ ]:
summary(model, input_size=(10, 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

# using sequential containers

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
         nn.Linear(num_features,3),
         nn.ReLU(),
         nn.Linear(3,1),
         nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out

In [ ]:
#create dataset
features=torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forwarc pass
model(features)

tensor([[0.5033],
        [0.5121],
        [0.5153],
        [0.4885],
        [0.4780],
        [0.4844],
        [0.5000],
        [0.4651],
        [0.4750],
        [0.4510]], grad_fn=<SigmoidBackward0>)

In [ ]:
summary(model, input_size=(10, 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch
import torch.nn as nn

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 0.88504945,  1.20228227,  0.93120584, ...,  1.14815965,
         0.62968993,  2.70366588],
       [-1.25569296, -0.49924791, -1.24453428, ..., -0.91075686,
         0.1204581 , -0.54685205],
       [-1.89434973,  1.41820058, -1.86314369, ..., -1.00108986,
        -0.19231084,  1.2271411 ],
       ...,
       [-0.40103283, -0.45465609, -0.39044597, ..., -0.49473344,
        -1.4528168 , -0.72371051],
       [-0.83070123, -1.22914568, -0.86819233, ..., -1.59854742,
        -0.24260534, -1.08445851],
       [ 1.89053195, -0.48047241,  1.80523561, ...,  1.47538634,
        -0.35105286, -0.72262881]])

In [9]:
y_train

72     M
206    B
539    B
143    B
102    B
      ..
58     B
475    B
397    B
276    B
373    M
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1])

# Numpy arrays to Pytorch Tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

In [15]:
# Defining the model

In [16]:
import torch
import torch.nn as nn
class SimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear= nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,feature):
    out = self.linear(feature)
    out=self.sigmoid(out)
    return out

In [17]:
learning_rate = 0.1
epochs = 25

In [18]:
# define loss function
loss_function = nn.BCELoss()

In [20]:
# create model
model = SimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7850411534309387
Epoch: 2, Loss: 0.5912841558456421
Epoch: 3, Loss: 0.4872013330459595
Epoch: 4, Loss: 0.4228304922580719
Epoch: 5, Loss: 0.3787464201450348
Epoch: 6, Loss: 0.3464048206806183
Epoch: 7, Loss: 0.32148832082748413
Epoch: 8, Loss: 0.30158162117004395
Epoch: 9, Loss: 0.2852265536785126
Epoch: 10, Loss: 0.2714897096157074
Epoch: 11, Loss: 0.2597449719905853
Epoch: 12, Loss: 0.24955587089061737
Epoch: 13, Loss: 0.240608349442482
Epoch: 14, Loss: 0.23267021775245667
Epoch: 15, Loss: 0.22556599974632263
Epoch: 16, Loss: 0.219160258769989
Epoch: 17, Loss: 0.2133466601371765
Epoch: 18, Loss: 0.20804044604301453
Epoch: 19, Loss: 0.20317308604717255
Epoch: 20, Loss: 0.1986885964870453
Epoch: 21, Loss: 0.19454054534435272
Epoch: 22, Loss: 0.19069015979766846
Epoch: 23, Loss: 0.18710476160049438
Epoch: 24, Loss: 0.1837565004825592
Epoch: 25, Loss: 0.18062147498130798

In [21]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6151123642921448